'use client'

import { useEffect, useRef, useState } from 'react'
import mapboxgl from 'mapbox-gl'
import 'mapbox-gl/dist/mapbox-gl.css'

type Booking = { id: string; traveler?: string; phone?: string; pax: number; pickup: string }
type Assigned = Record<string, number>
const TOKEN = 'pk.eyJ1Ijoib3VjaGluNTVlZGN4IiwiYSI6ImNtaXJ1MzVrNDA2Y2ozY3NhOXoxcng3NnEifQ.6yBtRfXRlgQ8vlmsYrRS2w'
function coords(value: string) { const s = decodeURIComponent(String(value || '')).replace(/\\u003d/g, '=').replace(/\\u0026/g, '&').replace(/&amp;/g, '&'); const patterns = [/!3d(-?\d+(?:\.\d+)?)!4d(-?\d+(?:\.\d+)?)/, /@(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/, /(?:query|ll|center)=(-?\d+(?:\.\d+)?)[,%20]+(-?\d+(?:\.\d+)?)/i, /[?&](?:lat|latitude)=(-?\d+(?:\.\d+)?)[^#&]+(?:lng|lon|longitude)=(-?\d+(?:\.\d+)?)/i]; for (const pattern of patterns) { const m = s.match(pattern); if (!m) continue; const lat = Number(m[1]); const lng = Number(m[2]); if (Number.isFinite(lat) && Number.isFinite(lng) && Math.abs(lat) <= 90 && Math.abs(lng) <= 180) return { lat, lng } } return null }
async function resolveCoords(value: string) { const direct = coords(value); if (direct) return direct; try { const r = await fetch(`/api/geocode?url=${encodeURIComponent(value)}`); return r.ok ? await r.json() : null } catch { return null } }
function total(items: Booking[]) { return items.reduce((n, b) => n + Number(b.pax || 0), 0) }
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] || char)) }

export default function MapClient() {
  const mapRef = useRef<HTMLDivElement>(null); const map = useRef<mapboxgl.Map | null>(null)
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [bookings, setBookings] = useState<Booking[]>([]); const [locations, setLocations] = useState<Record<string, { lat: number; lng: number }>>({}); const [assigned, setAssigned] = useState<Assigned>({}); const [selected, setSelected] = useState<number | null>(null); const [mapReady, setMapReady] = useState(false)
  const pax = total(bookings)
  async function load() { const r = await fetch(`/api/bookings?date=${date}`); const data = await r.json(); setBookings(data.bookings || []); setAssigned(data.assignments || {}) }
  useEffect(() => { load() }, [date])
  useEffect(() => { mapboxgl.accessToken = TOKEN; if (!mapRef.current || map.current) return; map.current = new mapboxgl.Map({ container: mapRef.current, style: 'mapbox://styles/mapbox/dark-v11', center: [-7.5898, 31.6295], zoom: 11 }); map.current.addControl(new mapboxgl.NavigationControl(), 'top-right'); const resize = () => map.current?.resize(); map.current.on('load', () => { resize(); setMapReady(true) }); const ro = new ResizeObserver(resize); ro.observe(mapRef.current); return () => { ro.disconnect(); map.current?.remove(); map.current = null } }, [])
  useEffect(() => { let cancelled = false; if (!bookings.length) { setLocations({}); return } Promise.all(bookings.map(async b => [b.id, await resolveCoords(b.pickup)] as const)).then(entries => { if (cancelled) return; const next = Object.fromEntries(entries.filter((entry): entry is [string, { lat: number; lng: number }] => Boolean(entry[1]))); setLocations(next); console.log('[v0] map locations:', { total: bookings.length, valid: Object.keys(next).length, missing: bookings.length - Object.keys(next).length, firstFive: Object.entries(next).slice(0, 5) }) }); return () => { cancelled = true } }, [bookings])
  useEffect(() => { if (!map.current || !mapReady) return; const points = Object.values(locations); if (!points.length) { map.current.flyTo({ center: [-7.5898, 31.6295], zoom: 11, duration: 900 }); return } if (points.length === 1) { map.current.flyTo({ center: [points[0].lng, points[0].lat], zoom: 14, duration: 900 }); return } const bounds = new mapboxgl.LngLatBounds(); points.forEach(p => bounds.extend([p.lng, p.lat])); map.current.fitBounds(bounds, { padding: 90, maxZoom: 14, duration: 900 }) }, [locations, mapReady])
  useEffect(() => { if (!map.current || !mapReady) return; const markers: mapboxgl.Marker[] = []; const occupied = new Map<string, number>(); bookings.forEach(b => { const p = locations[b.id]; if (!p) return; const key = `${p.lat.toFixed(5)},${p.lng.toFixed(5)}`; const index = occupied.get(key) || 0; occupied.set(key, index + 1); const ring = index === 0 ? { lat: 0, lng: 0 } : { lat: Math.cos(index * 1.7) * 0.00035 * Math.ceil(index / 8), lng: Math.sin(index * 1.7) * 0.00035 * Math.ceil(index / 8) }; const visualPoint = { lat: p.lat + ring.lat, lng: p.lng + ring.lng }; const group = assigned[b.id]; const active = selected === null || group === selected; const el = document.createElement('button'); el.textContent = String(b.pax); el.title = `${b.traveler || 'Booking'} · ${b.pax} pax`; el.style.cssText = `width:34px;height:34px;border-radius:50%;border:2px solid white;background:${group ? ['#38bdf8','#a78bfa','#34d399','#fb7185','#fbbf24'][((group || 1) - 1) % 5] : '#f59e0b'};opacity:${active ? 1 : .25};font-weight:800;cursor:pointer`; const popup = new mapboxgl.Popup({ closeButton: true, closeOnClick: false }).setHTML(`<div style="min-width:220px;line-height:1.5"><strong>${escapeHtml(b.traveler || 'Unnamed traveler')}</strong><br/><span>${b.pax} pax</span><br/><small>${escapeHtml(b.pickup)}</small><br/><small>${p.lat.toFixed(6)}, ${p.lng.toFixed(6)}</small></div>`); const marker = new mapboxgl.Marker(el).setLngLat([visualPoint.lng, visualPoint.lat]).setPopup(popup).addTo(map.current!); el.onclick = (event) => { event.stopPropagation(); setSelected(group || null); popup.addTo(map.current!); }; markers.push(marker) }); return () => markers.forEach(m => m.remove()) }, [bookings, locations, assigned, selected, mapReady])
  return <main className="fixed inset-0 bg-background"><div ref={mapRef} className="absolute inset-0 h-full w-full" /><div className="absolute left-4 top-4 z-10 rounded-2xl border border-border bg-card/95 px-4 py-3 shadow-xl backdrop-blur"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Pickup map</p><p className="mt-1 text-sm font-semibold">{bookings.length} bookings · {pax} pax</p><p className="mt-1 text-xs text-muted-foreground">Click a marker to view traveler and pax</p></div><div className="absolute right-4 top-4 z-10"><input aria-label="Travel date" type="date" value={date} onChange={e => setDate(e.target.value)} className="rounded-xl border border-border bg-card/95 px-3 py-2 text-sm shadow-xl backdrop-blur" /></div></main>
}
