'use client'

import { useEffect, useRef, useState } from 'react'
import mapboxgl from 'mapbox-gl'
import 'mapbox-gl/dist/mapbox-gl.css'

type Booking = { id: string; traveler?: string; phone?: string; pax: number; pickup: string }
type Assigned = Record<string, number>
const TOKEN = 'pk.eyJ1Ijoib3VjaGluNTVlZGN4IiwiYSI6ImNtaXJ1MzVrNDA2Y2ozY3NhOXoxcng3NnEifQ.6yBtRfXRlgQ8vlmsYrRS2w'
function coords(value: string) { const s = decodeURIComponent(value || ''); const m = s.match(/!3d(-?\d+(?:\.\d+)?)!4d(-?\d+(?:\.\d+)?)|@(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/); if (!m) return null; return { lat: Number(m[1] || m[3]), lng: Number(m[2] || m[4]) } }
function total(items: Booking[]) { return items.reduce((n, b) => n + Number(b.pax || 0), 0) }
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] || char)) }

export default function MapClient() {
  const mapRef = useRef<HTMLDivElement>(null); const map = useRef<mapboxgl.Map | null>(null)
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [bookings, setBookings] = useState<Booking[]>([]); const [assigned, setAssigned] = useState<Assigned>({}); const [selected, setSelected] = useState<number | null>(null)
  const pax = total(bookings)
  async function load() { const r = await fetch(`/api/bookings?date=${date}`); const data = await r.json(); setBookings(data.bookings || []); setAssigned(data.assignments || {}) }
  useEffect(() => { load() }, [date])
  useEffect(() => { mapboxgl.accessToken = TOKEN; if (!mapRef.current || map.current) return; map.current = new mapboxgl.Map({ container: mapRef.current, style: 'mapbox://styles/mapbox/dark-v11', center: [-7.5898, 31.6295], zoom: 11 }); map.current.addControl(new mapboxgl.NavigationControl(), 'top-right'); const resize = () => map.current?.resize(); map.current.on('load', resize); const ro = new ResizeObserver(resize); ro.observe(mapRef.current); return () => { ro.disconnect(); map.current?.remove(); map.current = null } }, [])
  useEffect(() => { if (!map.current || !bookings.length) return; const points = bookings.map(b => coords(b.pickup)).filter((p): p is { lat: number; lng: number } => Boolean(p)); if (!points.length) { map.current.flyTo({ center: [-7.5898, 31.6295], zoom: 11, duration: 900 }); } else if (points.length === 1) { map.current.flyTo({ center: [points[0].lng, points[0].lat], zoom: 14, duration: 900 }); } else { const bounds = new mapboxgl.LngLatBounds(); points.forEach(p => bounds.extend([p.lng, p.lat])); map.current.fitBounds(bounds, { padding: 90, maxZoom: 14, duration: 900 }); } }, [bookings, date])
  useEffect(() => { if (!map.current) return; const markers: mapboxgl.Marker[] = []; bookings.forEach(b => { const p = coords(b.pickup); if (!p) return; const group = assigned[b.id]; const active = selected === null || group === selected; const el = document.createElement('button'); el.textContent = String(b.pax); el.title = `${b.id} · ${b.pax} pax`; el.style.cssText = `width:32px;height:32px;border-radius:50%;border:2px solid white;background:${group ? ['#38bdf8','#a78bfa','#34d399','#fb7185','#fbbf24'][((group || 1) - 1) % 5] : '#f59e0b'};opacity:${active ? 1 : .25};font-weight:800;cursor:pointer`; const popup = new mapboxgl.Popup({ closeButton: true, closeOnClick: false }).setHTML(`<div style="min-width:220px;line-height:1.5"><strong>${escapeHtml(b.traveler || 'Unnamed traveler')}</strong><br/><span>${b.pax} pax</span>${b.phone ? `<br/><small>${escapeHtml(b.phone)}</small>` : ''}<br/><small style="display:block;margin-top:4px;color:#64748b">Pickup location</small><span>${escapeHtml(b.pickup)}</span><br/><small style="color:#64748b">${p.lat.toFixed(6)}, ${p.lng.toFixed(6)}</small></div>`); const marker = new mapboxgl.Marker(el).setLngLat([p.lng, p.lat]).setPopup(popup).addTo(map.current!); el.onclick = (event) => { event.stopPropagation(); setSelected(group || null); popup.addTo(map.current!); }; markers.push(marker) }); return () => markers.forEach(m => m.remove()) }, [bookings, assigned, selected])
  return <main className="fixed inset-0 bg-background"><div ref={mapRef} className="absolute inset-0 h-full w-full" /><div className="absolute left-4 top-4 z-10 rounded-2xl border border-border bg-card/95 px-4 py-3 shadow-xl backdrop-blur"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Pickup map</p><p className="mt-1 text-sm font-semibold">{bookings.length} bookings · {pax} pax</p><p className="mt-1 text-xs text-muted-foreground">Click a marker to view traveler and pax</p></div><div className="absolute right-4 top-4 z-10"><input aria-label="Travel date" type="date" value={date} onChange={e => setDate(e.target.value)} className="rounded-xl border border-border bg-card/95 px-3 py-2 text-sm shadow-xl backdrop-blur" /></div></main>
}
